"""create customconnectortemplate

Revision ID: 8615ac51e78b
Revises: 1f61c765cd1c
Create Date: 2022-12-24 07:11:52.634508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8615ac51e78b'
down_revision = '1f61c765cd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customconnectortemplate',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.String(), nullable=False),
    sa.Column('dataset', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('functions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customconnectortemplate_id'), 'customconnectortemplate', ['id'], unique=False)
    op.create_index(op.f('ix_customconnectortemplate_key'), 'customconnectortemplate', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customconnectortemplate_key'), table_name='customconnectortemplate')
    op.drop_index(op.f('ix_customconnectortemplate_id'), table_name='customconnectortemplate')
    op.drop_table('customconnectortemplate')
    # ### end Alembic commands ###
